// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-j0GckDrr7zDHTN-0qGe4wtH1y4PxYU',
    appId: '1:129069509062:web:287641606c895ddda2aac7',
    messagingSenderId: '129069509062',
    projectId: 'capmus-events',
    authDomain: 'capmus-events.firebaseapp.com',
    storageBucket: 'capmus-events.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtbPZ2TU4bF5GOyWBnsKDFa2iip6Q0Fz4',
    appId: '1:129069509062:android:eda692d521877902a2aac7',
    messagingSenderId: '129069509062',
    projectId: 'capmus-events',
    storageBucket: 'capmus-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Loy6n-fQ8yderezd9NZKwDbPataf-TU',
    appId: '1:129069509062:ios:1f7206bc2ed4bd7ea2aac7',
    messagingSenderId: '129069509062',
    projectId: 'capmus-events',
    storageBucket: 'capmus-events.firebasestorage.app',
    iosBundleId: 'com.example.campusEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Loy6n-fQ8yderezd9NZKwDbPataf-TU',
    appId: '1:129069509062:ios:1f7206bc2ed4bd7ea2aac7',
    messagingSenderId: '129069509062',
    projectId: 'capmus-events',
    storageBucket: 'capmus-events.firebasestorage.app',
    iosBundleId: 'com.example.campusEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi-j0GckDrr7zDHTN-0qGe4wtH1y4PxYU',
    appId: '1:129069509062:web:4517891a5c8bafeaa2aac7',
    messagingSenderId: '129069509062',
    projectId: 'capmus-events',
    authDomain: 'capmus-events.firebaseapp.com',
    storageBucket: 'capmus-events.firebasestorage.app',
  );
}
